name: todaily
description: "Daily Journal."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+04

environment:
  sdk: ^3.11.5

dependencies:
  flex_color_scheme: ^8.4.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_launcher_icons: ^0.14.4
  flutter_quill: ^11.5.0
  google_fonts: ^8.1.0
  hive_ce: ^2.19.3
  hive_ce_flutter: ^2.3.4
  intl: ^0.20.2
  lucide_icons_flutter: ^3.1.13
  path: ^1.9.1
  path_provider: ^2.1.5
  signals: ^6.3.0
  very_good_analysis: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.15.0
  hive_ce_generator: ^1.11.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
