name: todaily
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0-278.2.beta

dependencies:
  firebase_core: ^3.13.0
  flex_color_scheme: ^8.2.0
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.8.0
  google_fonts: ^6.2.1
  hive_ce: ^2.11.1
  hive_ce_flutter: ^2.3.0
  hive_flutter: ^1.1.0
  html: ^0.15.6
  image_picker: ^1.1.2
  intl: ^0.20.2
  logger: ^2.5.0
  path_provider: ^2.1.5
  signals: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
