// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2sJuQaKcjO9ZcEfy9Df-f5rwSOlSlcno',
    appId: '1:70198882080:web:d16877fe4e7b06b8f97145',
    messagingSenderId: '70198882080',
    projectId: 'todailyapp',
    authDomain: 'todailyapp.firebaseapp.com',
    storageBucket: 'todailyapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoJm-dpFxsC1si-FbVemAHdSQrHtiisMs',
    appId: '1:70198882080:android:50f68347ee32890ef97145',
    messagingSenderId: '70198882080',
    projectId: 'todailyapp',
    storageBucket: 'todailyapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7i1QpHRikIikHe9d-UkMrXoskuqXY7CQ',
    appId: '1:70198882080:ios:5853b282c26780fcf97145',
    messagingSenderId: '70198882080',
    projectId: 'todailyapp',
    storageBucket: 'todailyapp.firebasestorage.app',
    iosBundleId: 'dev.plotsklapps.todaily',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7i1QpHRikIikHe9d-UkMrXoskuqXY7CQ',
    appId: '1:70198882080:ios:5853b282c26780fcf97145',
    messagingSenderId: '70198882080',
    projectId: 'todailyapp',
    storageBucket: 'todailyapp.firebasestorage.app',
    iosBundleId: 'dev.plotsklapps.todaily',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2sJuQaKcjO9ZcEfy9Df-f5rwSOlSlcno',
    appId: '1:70198882080:web:2782b750d8464177f97145',
    messagingSenderId: '70198882080',
    projectId: 'todailyapp',
    authDomain: 'todailyapp.firebaseapp.com',
    storageBucket: 'todailyapp.firebasestorage.app',
  );

}