import 'package:flutter/material.dart';
import 'package:hugeicons/hugeicons.dart';
import 'package:signals/signals_flutter.dart';

final Signal<List<String>> sAvailableEmojis = Signal<List<String>>(
  kEmojiMap.keys.toList(),
  debugLabel: 'sAvailableEmojis',
);

Widget getEmojiWidget(String key) {
  return HugeIcon(icon: kEmojiMap[key]!);
}

final Map<String, List<List<dynamic>>> kEmojiMap =
    <String, List<List<dynamic>>>{
      'Angel': HugeIcons.strokeRoundedAngel,
      'Angry': HugeIcons.strokeRoundedAngry,
      'Confused': HugeIcons.strokeRoundedConfused,
      'Crazy': HugeIcons.strokeRoundedCrazy,
      'Crying': HugeIcons.strokeRoundedCrying,
      'Dead': HugeIcons.strokeRoundedDead,
      'Displeased': HugeIcons.strokeRoundedDispleased,
      'Drooling': HugeIcons.strokeRoundedDrooling,
      'Evil': HugeIcons.strokeRoundedEvil,
      'Flushed': HugeIcons.strokeRoundedFlushed,
      'Grimacing': HugeIcons.strokeRoundedGrimacing,
      'Grinning': HugeIcons.strokeRoundedGrinning,
      'Happy': HugeIcons.strokeRoundedHappy,
      'Happy01': HugeIcons.strokeRoundedHappy01,
      'InLove': HugeIcons.strokeRoundedInLove,
      'Kid': HugeIcons.strokeRoundedKid,
      'Kissing': HugeIcons.strokeRoundedKissing,
      'Laughing': HugeIcons.strokeRoundedLaughing,
      'LookBottom': HugeIcons.strokeRoundedLookBottom,
      'LookLeft': HugeIcons.strokeRoundedLookLeft,
      'LookRight': HugeIcons.strokeRoundedLookRight,
      'LookTop': HugeIcons.strokeRoundedLookTop,
      'MedicalMask': HugeIcons.strokeRoundedMedicalMask,
      'Meh': HugeIcons.strokeRoundedMeh,
      'Monocle': HugeIcons.strokeRoundedMonocle01,
      'Nerd': HugeIcons.strokeRoundedNerd,
      'Mute': HugeIcons.strokeRoundedMute,
      'Pensive': HugeIcons.strokeRoundedPensive,
      'Relieved01': HugeIcons.strokeRoundedRelieved01,
      'Relieved02': HugeIcons.strokeRoundedRelieved02,
      'Sad01': HugeIcons.strokeRoundedSad01,
      'Sad02': HugeIcons.strokeRoundedSad02,
      'SadDizzy': HugeIcons.strokeRoundedSadDizzy,
      'Senseless': HugeIcons.strokeRoundedSenseless,
      'Shocked': HugeIcons.strokeRoundedShocked,
      'Silence': HugeIcons.strokeRoundedSilence,
      'SingLeft': HugeIcons.strokeRoundedSingLeft,
      'SingRight': HugeIcons.strokeRoundedSingRight,
      'Sleeping': HugeIcons.strokeRoundedSleeping,
      'Smart': HugeIcons.strokeRoundedSmart,
      'Smile': HugeIcons.strokeRoundedSmile,
      'SmileDizzy': HugeIcons.strokeRoundedSmileDizzy,
      'SmilePlus': HugeIcons.strokeRoundedSmilePlus,
      'StarFace': HugeIcons.strokeRoundedStarFace,
      'Sticker': HugeIcons.strokeRoundedSticker,
      'Sunglasses': HugeIcons.strokeRoundedSunglasses,
      'Surprise': HugeIcons.strokeRoundedSurprise,
      'Suspicious': HugeIcons.strokeRoundedSuspicious,
      'Tired01': HugeIcons.strokeRoundedTired01,
      'Tired02': HugeIcons.strokeRoundedTired02,
      'Tongue01': HugeIcons.strokeRoundedTongue,
      'Tongue02': HugeIcons.strokeRoundedTongue01,
      'TongueWinkLeft': HugeIcons.strokeRoundedTongueWinkLeft,
      'TongueWinkRight': HugeIcons.strokeRoundedTongueWinkRight,
      'Unamused': HugeIcons.strokeRoundedUnamused,
      'Unhappy': HugeIcons.strokeRoundedUnhappy,
      'Vomiting': HugeIcons.strokeRoundedVomiting,
      'Wink': HugeIcons.strokeRoundedWink,
      'Winking': HugeIcons.strokeRoundedWinking,
      'Worry': HugeIcons.strokeRoundedWorry,
    };
