import 'package:flex_color_scheme/flex_color_scheme.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:todaily/services/signal_service.dart';

const Color kPink = Color(0xFFEBA1A6);
const Color kPurple = Color(0xFF815AA3);
const Color kOrange = Color(0xFFFCB075);

// Override textTheme for the XL fonts.
final TextTheme _textThemeOverrides = TextTheme(
  displayLarge: GoogleFonts.getFont('Questrial'),
  displayMedium: GoogleFonts.getFont('Questrial'),
  displaySmall: GoogleFonts.getFont('Questrial'),
);

final Computed<ThemeData> cThemeData = Computed<ThemeData>(() {
  final FlexScheme activeScheme = sFlexScheme.value;

  if (sDarkMode.value) {
    return FlexThemeData.dark(
      // Using FlexColorScheme built-in FlexScheme enum based colors.
      scheme: activeScheme,
      // None seed generated ColorScheme style of Fixed colors.
      fixedColorStyle: FlexFixedColorStyle.computed,
      // Convenience direct styling properties.
      tabBarStyle: FlexTabBarStyle.forAppBar,
      // Component theme configurations for dark mode.
      subThemesData: const FlexSubThemesData(
        interactionEffects: true,
        tintedDisabledControls: true,
        blendOnColors: true,
        useMaterial3Typography: true,
        splashType: FlexSplashType.inkSplash,
        defaultRadius: 8,
        thinBorderWidth: 1,
        thickBorderWidth: 2,
        filledButtonSchemeColor: SchemeColor.secondary,
        elevatedButtonSchemeColor: SchemeColor.secondary,
        outlinedButtonSchemeColor: SchemeColor.secondary,
        outlinedButtonOutlineSchemeColor: SchemeColor.secondary,
        toggleButtonsSchemeColor: SchemeColor.secondary,
        toggleButtonsSelectedForegroundSchemeColor: SchemeColor.onSecondary,
        toggleButtonsUnselectedSchemeColor: SchemeColor.primary,
        segmentedButtonSchemeColor: SchemeColor.secondary,
        segmentedButtonSelectedForegroundSchemeColor: SchemeColor.onSecondary,
        segmentedButtonUnselectedSchemeColor: SchemeColor.surface,
        segmentedButtonUnselectedForegroundSchemeColor: SchemeColor.onSurface,
        segmentedButtonBorderSchemeColor: SchemeColor.outline,
        switchSchemeColor: SchemeColor.secondary,
        switchThumbSchemeColor: SchemeColor.primaryContainer,
        switchAdaptiveCupertinoLike: FlexAdaptive.all(),
        checkboxSchemeColor: SchemeColor.secondary,
        radioSchemeColor: SchemeColor.secondary,
        unselectedToggleIsColored: true,
        sliderBaseSchemeColor: SchemeColor.primary,
        sliderThumbSchemeColor: SchemeColor.secondary,
        sliderIndicatorSchemeColor: SchemeColor.secondary,
        sliderValueTinted: true,
        sliderValueIndicatorType: FlexSliderIndicatorType.rounded,
        sliderShowValueIndicator: ShowValueIndicator.onDrag,
        sliderTrackHeight: 24,
        sliderYear2023: false,
        progressIndicatorYear2023: false,
        progressIndicatorBaseSchemeColor: SchemeColor.primary,
        progressIndicatorLinearTrackSchemeColor: SchemeColor.secondary,
        progressIndicatorCircularTrackSchemeColor: SchemeColor.secondary,
        progressIndicatorStopIndicatorSchemeColor: SchemeColor.primary,
        progressIndicatorLinearMinHeight: 6,
        progressIndicatorLinearRadius: 12,
        progressIndicatorStopIndicatorRadius: 12,
        progressIndicatorStrokeWidth: 6,
        progressIndicatorStrokeAlign: -0.8,
        progressIndicatorTrackGap: 6,
        progressIndicatorStrokeCap: StrokeCap.round,
        progressIndicatorConstraints: BoxConstraints(
          minWidth: 40,
          minHeight: 40,
        ),
        progressIndicatorCircularTrackPadding: EdgeInsetsDirectional.fromSTEB(
          2,
          2,
          2,
          2,
        ),
        inputDecoratorSchemeColor: SchemeColor.primary,
        inputDecoratorIsFilled: true,
        inputDecoratorContentPadding: EdgeInsetsDirectional.fromSTEB(
          12,
          16,
          12,
          12,
        ),
        inputDecoratorBackgroundAlpha: 40,
        inputDecoratorBorderSchemeColor: SchemeColor.primary,
        inputDecoratorBorderType: FlexInputBorderType.outline,
        inputDecoratorRadius: 8,
        inputDecoratorUnfocusedBorderIsColored: true,
        inputDecoratorBorderWidth: 1,
        inputDecoratorFocusedBorderWidth: 2,
        inputDecoratorPrefixIconSchemeColor: SchemeColor.primaryFixed,
        inputDecoratorSuffixIconSchemeColor: SchemeColor.primary,
        inputCursorSchemeColor: SchemeColor.primary,
        inputSelectionSchemeColor: SchemeColor.primary,
        inputSelectionHandleSchemeColor: SchemeColor.primary,
        listTileSelectedSchemeColor: SchemeColor.primary,
        listTileIconSchemeColor: SchemeColor.onSurfaceVariant,
        listTileContentPadding: EdgeInsetsDirectional.fromSTEB(16, 0, 16, 0),
        listTileMinVerticalPadding: 6,
        fabSchemeColor: SchemeColor.primaryContainer,
        fabForegroundSchemeColor: SchemeColor.onPrimaryContainer,
        chipSchemeColor: SchemeColor.surface,
        chipSelectedSchemeColor: SchemeColor.onSecondary,
        chipSecondarySelectedSchemeColor: SchemeColor.secondary,
        chipDeleteIconSchemeColor: SchemeColor.onSurfaceVariant,
        chipBlendColors: false,
        chipIconSize: 16,
        chipPadding: EdgeInsetsDirectional.fromSTEB(10, 10, 10, 10),
        cardBackgroundSchemeColor: SchemeColor.surfaceContainerLow,
        cardElevation: 0,
        popupMenuRadius: 8,
        popupMenuSchemeColor: SchemeColor.surfaceContainer,
        alignedDropdown: true,
        dialogBackgroundSchemeColor: SchemeColor.surfaceContainerHigh,
        useInputDecoratorThemeInDialogs: true,
        datePickerHeaderBackgroundSchemeColor: SchemeColor.surfaceContainerHigh,
        datePickerHeaderForegroundSchemeColor: SchemeColor.onSurfaceVariant,
        datePickerDividerSchemeColor: SchemeColor.secondary,
        snackBarRadius: 8,
        snackBarActionSchemeColor: SchemeColor.inversePrimary,
        bottomAppBarSchemeColor: SchemeColor.surfaceContainer,
        bottomAppBarHeight: 76,
        tabBarIndicatorSchemeColor: SchemeColor.secondary,
        tabBarIndicatorSize: TabBarIndicatorSize.label,
        tabBarIndicatorWeight: 4,
        tabBarIndicatorTopRadius: 8,
        tabBarTabAlignment: TabAlignment.fill,
        tabBarIndicatorAnimation: TabIndicatorAnimation.elastic,
        drawerBackgroundSchemeColor: SchemeColor.surfaceContainerLow,
        drawerWidth: 300,
        drawerIndicatorSchemeColor: SchemeColor.secondary,
        drawerSelectedItemSchemeColor: SchemeColor.onSecondary,
        drawerUnselectedItemSchemeColor: SchemeColor.onSurfaceVariant,
        bottomSheetBackgroundColor: SchemeColor.surfaceContainerLow,
        bottomSheetModalBackgroundColor: SchemeColor.surfaceContainerLow,
        bottomSheetElevation: 1,
        bottomSheetModalElevation: 3,
        bottomSheetClipBehavior: Clip.antiAlias,
        bottomNavigationBarSelectedLabelSchemeColor:
            SchemeColor.onSurfaceVariant,
        bottomNavigationBarUnselectedLabelSchemeColor: SchemeColor.primary,
        bottomNavigationBarMutedUnselectedLabel: true,
        bottomNavigationBarSelectedIconSchemeColor:
            SchemeColor.onSurfaceVariant,
        bottomNavigationBarUnselectedIconSchemeColor: SchemeColor.primary,
        bottomNavigationBarMutedUnselectedIcon: true,
        bottomNavigationBarBackgroundSchemeColor: SchemeColor.surface,
        bottomNavigationBarUnselectedIconSize: 22,
        menuRadius: 8,
        menuSchemeColor: SchemeColor.surfaceContainer,
        menuItemBackgroundSchemeColor: SchemeColor.surfaceContainer,
        menuItemForegroundSchemeColor: SchemeColor.onSurface,
        searchBarBackgroundSchemeColor: SchemeColor.surfaceContainerHigh,
        searchViewBackgroundSchemeColor: SchemeColor.surfaceContainerHigh,
        searchBarRadius: 8,
        searchBarElevation: 0,
        searchViewRadius: 8,
        searchViewHeaderHeight: 56,
        searchUseGlobalShape: true,
        navigationBarSelectedLabelSchemeColor: SchemeColor.onSurface,
        navigationBarUnselectedLabelSchemeColor: SchemeColor.onSurfaceVariant,
        navigationBarMutedUnselectedLabel: true,
        navigationBarSelectedIconSchemeColor: SchemeColor.onSecondary,
        navigationBarUnselectedIconSchemeColor: SchemeColor.onSurfaceVariant,
        navigationBarMutedUnselectedIcon: true,
        navigationBarIndicatorSchemeColor: SchemeColor.secondary,
        navigationBarIndicatorRadius: 8,
        navigationBarBackgroundSchemeColor: SchemeColor.surfaceContainer,
        navigationBarHeight: 76,
        navigationBarLabelBehavior:
            NavigationDestinationLabelBehavior.onlyShowSelected,
        navigationRailMutedUnselectedLabel: true,
        navigationRailMutedUnselectedIcon: true,
        navigationRailUseIndicator: true,
        navigationRailIndicatorSchemeColor: SchemeColor.secondary,
        navigationRailBackgroundSchemeColor: SchemeColor.surface,
        navigationRailLabelType: NavigationRailLabelType.selected,
      ),
      // Direct ThemeData properties.
      visualDensity: VisualDensity.comfortable,
      materialTapTargetSize: MaterialTapTargetSize.padded,
      cupertinoOverrideTheme: const CupertinoThemeData(applyThemeToAll: true),
      fontFamily: GoogleFonts.getFont(sFont.value).fontFamily,
      textTheme: _textThemeOverrides,
    );
  } else {
    return FlexThemeData.light(
      // Using FlexColorScheme built-in FlexScheme enum based colors
      scheme: activeScheme,
      // None seed generated ColorScheme style of Fixed colors.
      fixedColorStyle: FlexFixedColorStyle.computed,
      // Convenience direct styling properties.
      tabBarStyle: FlexTabBarStyle.forAppBar,
      // Component theme configurations for light mode.
      subThemesData: const FlexSubThemesData(
        interactionEffects: true,
        tintedDisabledControls: true,
        useMaterial3Typography: true,
        thinBorderWidth: 1,
        thickBorderWidth: 2,
        splashType: FlexSplashType.inkSplash,
        defaultRadius: 8,
        filledButtonSchemeColor: SchemeColor.secondary,
        elevatedButtonSchemeColor: SchemeColor.secondary,
        outlinedButtonSchemeColor: SchemeColor.secondary,
        outlinedButtonOutlineSchemeColor: SchemeColor.secondary,
        toggleButtonsSchemeColor: SchemeColor.secondary,
        toggleButtonsSelectedForegroundSchemeColor: SchemeColor.onSecondary,
        toggleButtonsUnselectedSchemeColor: SchemeColor.primary,
        segmentedButtonSchemeColor: SchemeColor.secondary,
        segmentedButtonSelectedForegroundSchemeColor: SchemeColor.onSecondary,
        segmentedButtonUnselectedSchemeColor: SchemeColor.surface,
        segmentedButtonUnselectedForegroundSchemeColor: SchemeColor.onSurface,
        segmentedButtonBorderSchemeColor: SchemeColor.outline,
        switchSchemeColor: SchemeColor.secondary,
        switchThumbSchemeColor: SchemeColor.primaryContainer,
        switchAdaptiveCupertinoLike: FlexAdaptive.all(),
        checkboxSchemeColor: SchemeColor.secondary,
        radioSchemeColor: SchemeColor.secondary,
        unselectedToggleIsColored: true,
        sliderBaseSchemeColor: SchemeColor.primary,
        sliderThumbSchemeColor: SchemeColor.secondary,
        sliderIndicatorSchemeColor: SchemeColor.secondary,
        sliderValueTinted: true,
        sliderValueIndicatorType: FlexSliderIndicatorType.rounded,
        sliderShowValueIndicator: ShowValueIndicator.onDrag,
        sliderTrackHeight: 24,
        sliderYear2023: false,
        progressIndicatorYear2023: false,
        progressIndicatorBaseSchemeColor: SchemeColor.primary,
        progressIndicatorLinearTrackSchemeColor: SchemeColor.secondary,
        progressIndicatorCircularTrackSchemeColor: SchemeColor.secondary,
        progressIndicatorStopIndicatorSchemeColor: SchemeColor.primary,
        progressIndicatorLinearMinHeight: 6,
        progressIndicatorLinearRadius: 12,
        progressIndicatorStopIndicatorRadius: 12,
        progressIndicatorStrokeWidth: 6,
        progressIndicatorStrokeAlign: -0.8,
        progressIndicatorTrackGap: 6,
        progressIndicatorStrokeCap: StrokeCap.round,
        progressIndicatorConstraints: BoxConstraints(
          minWidth: 40,
          minHeight: 40,
        ),
        progressIndicatorCircularTrackPadding: EdgeInsetsDirectional.fromSTEB(
          2,
          2,
          2,
          2,
        ),
        inputDecoratorSchemeColor: SchemeColor.primary,
        inputDecoratorIsFilled: true,
        inputDecoratorContentPadding: EdgeInsetsDirectional.fromSTEB(
          12,
          16,
          12,
          12,
        ),
        inputDecoratorBackgroundAlpha: 7,
        inputDecoratorBorderSchemeColor: SchemeColor.primary,
        inputDecoratorBorderType: FlexInputBorderType.outline,
        inputDecoratorRadius: 8,
        inputDecoratorUnfocusedBorderIsColored: true,
        inputDecoratorBorderWidth: 1,
        inputDecoratorFocusedBorderWidth: 2,
        inputDecoratorPrefixIconSchemeColor: SchemeColor.onPrimaryFixedVariant,
        inputDecoratorSuffixIconSchemeColor: SchemeColor.primary,
        listTileSelectedSchemeColor: SchemeColor.primary,
        listTileIconSchemeColor: SchemeColor.onSurfaceVariant,
        listTileContentPadding: EdgeInsetsDirectional.fromSTEB(16, 0, 16, 0),
        listTileMinVerticalPadding: 6,
        fabSchemeColor: SchemeColor.primaryContainer,
        fabForegroundSchemeColor: SchemeColor.onPrimaryContainer,
        chipSchemeColor: SchemeColor.surface,
        chipSelectedSchemeColor: SchemeColor.secondary,
        chipSecondarySelectedSchemeColor: SchemeColor.secondary,
        chipDeleteIconSchemeColor: SchemeColor.onSurfaceVariant,
        chipBlendColors: false,
        chipIconSize: 24,
        chipPadding: EdgeInsetsDirectional.fromSTEB(10, 10, 10, 10),
        cardBackgroundSchemeColor: SchemeColor.surfaceContainerLow,
        cardElevation: 0,
        popupMenuRadius: 8,
        popupMenuSchemeColor: SchemeColor.surfaceContainer,
        alignedDropdown: true,
        useInputDecoratorThemeInDialogs: true,
        datePickerHeaderBackgroundSchemeColor: SchemeColor.surfaceContainerHigh,
        datePickerHeaderForegroundSchemeColor: SchemeColor.onSurfaceVariant,
        datePickerDividerSchemeColor: SchemeColor.secondary,
        snackBarRadius: 8,
        snackBarActionSchemeColor: SchemeColor.inversePrimary,
        bottomAppBarHeight: 76,
        tabBarIndicatorSize: TabBarIndicatorSize.label,
        tabBarIndicatorWeight: 4,
        tabBarIndicatorTopRadius: 8,
        tabBarTabAlignment: TabAlignment.fill,
        tabBarIndicatorAnimation: TabIndicatorAnimation.elastic,
        drawerBackgroundSchemeColor: SchemeColor.surfaceContainerLow,
        drawerWidth: 300,
        drawerIndicatorSchemeColor: SchemeColor.secondary,
        drawerSelectedItemSchemeColor: SchemeColor.onSecondary,
        drawerUnselectedItemSchemeColor: SchemeColor.onSurfaceVariant,
        bottomSheetBackgroundColor: SchemeColor.surfaceContainerLow,
        bottomSheetModalBackgroundColor: SchemeColor.surfaceContainerLow,
        bottomSheetElevation: 1,
        bottomSheetModalElevation: 3,
        bottomSheetClipBehavior: Clip.antiAlias,
        bottomNavigationBarSelectedLabelSchemeColor:
            SchemeColor.onSurfaceVariant,
        bottomNavigationBarUnselectedLabelSchemeColor: SchemeColor.primary,
        bottomNavigationBarMutedUnselectedLabel: true,
        bottomNavigationBarSelectedIconSchemeColor:
            SchemeColor.onSurfaceVariant,
        bottomNavigationBarUnselectedIconSchemeColor: SchemeColor.primary,
        bottomNavigationBarMutedUnselectedIcon: true,
        bottomNavigationBarBackgroundSchemeColor: SchemeColor.surface,
        bottomNavigationBarUnselectedIconSize: 22,
        menuRadius: 8,
        menuSchemeColor: SchemeColor.surfaceContainer,
        menuItemBackgroundSchemeColor: SchemeColor.surfaceContainer,
        menuItemForegroundSchemeColor: SchemeColor.onSurface,
        searchBarBackgroundSchemeColor: SchemeColor.surfaceContainerHigh,
        searchViewBackgroundSchemeColor: SchemeColor.surfaceContainerHigh,
        searchBarRadius: 8,
        searchBarElevation: 0,
        searchViewRadius: 8,
        searchViewHeaderHeight: 56,
        searchUseGlobalShape: true,
        navigationBarSelectedLabelSchemeColor: SchemeColor.onSurface,
        navigationBarUnselectedLabelSchemeColor: SchemeColor.onSurfaceVariant,
        navigationBarMutedUnselectedLabel: true,
        navigationBarSelectedIconSchemeColor: SchemeColor.onSecondary,
        navigationBarUnselectedIconSchemeColor: SchemeColor.onSurfaceVariant,
        navigationBarMutedUnselectedIcon: true,
        navigationBarIndicatorSchemeColor: SchemeColor.secondary,
        navigationBarIndicatorRadius: 8,
        navigationBarBackgroundSchemeColor: SchemeColor.surfaceContainer,
        navigationBarHeight: 76,
        navigationBarLabelBehavior:
            NavigationDestinationLabelBehavior.onlyShowSelected,
        navigationRailMutedUnselectedLabel: true,
        navigationRailMutedUnselectedIcon: true,
        navigationRailUseIndicator: true,
        navigationRailIndicatorSchemeColor: SchemeColor.secondary,
        navigationRailBackgroundSchemeColor: SchemeColor.surface,
        navigationRailLabelType: NavigationRailLabelType.selected,
      ),
      // Direct ThemeData properties.
      visualDensity: VisualDensity.comfortable,
      materialTapTargetSize: MaterialTapTargetSize.padded,
      cupertinoOverrideTheme: const CupertinoThemeData(applyThemeToAll: true),
      fontFamily: GoogleFonts.getFont(sFont.value).fontFamily,
      textTheme: _textThemeOverrides,
    );
  }
});
